name: Post-deployment tests
description: "Run post-deployment tests for this repo"

inputs:
  targetEnvironment:
    description: Name of the static environment under test
    required: true
    default: main

  targetAccountGroup:
    description: Name of the Account Group under test
    default: nhs-notify-iam-dev
    required: true

  targetComponent:
    description: Name of the Component under test
    default: app

runs:
  using: "composite"

  steps:
    - name: Fetch terraform output
      uses: actions/download-artifact@v4
      with:
        name: terraform-output-${{ inputs.targetComponent }}
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci

    - name: Generate outputs file
      shell: bash
      run: |
        root_dir=${GITHUB_WORKSPACE}
        mv ./terraform_output.json ./sandbox_tf_outputs.json
        npm run generate-outputs sandbox-output

    - name: Extract configuration details
      shell: bash
      run: |
        cat amplify_outputs.json | jq
        # echo USER_POOL_CLIENT_ID=$(cat amplify_outputs.json | jq -r .auth.user_pool_client_id.value) >> $GITHUB_ENV
        # echo USER_POOL_ID=$(cat amplify_outputs.json | jq -r .auth.user_pool_id.value) >> $GITHUB_ENV

    - name: Install playwright browsers
      shell: bash
      run: npx playwright install --with-deps

    - name: "Run UI test"
      shell: bash
      run: |
        cd tests/test-team
        npm run test:local-ui

    - name: "Run UI test"
      shell: bash
      run: |
        make test-ui

    - name: Archive UI test results
      uses: actions/upload-artifact@v4
      with:
        name: UI test report
        path: "tests/test-team/playwright-report"
