name: Call Notify Internal Infrastructure Deployment
## Sub workflow which plans and deploys Notify components as part of the workflow.
## Review Gates may be required to proceed on triggered builds.

on:
  workflow_call:
    inputs:
      infraRepoName:
        type: string
        description: Repository (this one) in the NHSDigital Github Org to deploy from
        default: nhs-notify-iam-webauth
      releaseVersion:
        type: string
        description: The Github release version, commit, or tag.
        default: main
      targetWorkflow:
        type: string
        description: The name of the github workflow to call.
        default: main
      targetEnvironment:
        type: string
        description: The Terraform environment to deploy
        default: main
      targetComponent:
        type: string
        description: The Terraform component to deploy
        required: true
      targetAccountGroup:
        type: string
        description: The Terraform group to deploy
        required: true
      terraformAction:
        type: string
        description: The Terraform component to deploy
        default: plan

concurrency:
  group: ${{ inputs.targetEnvironment }}-${{ inputs.targetAccountGroup }}-${{ inputs.targetComponent }}-${{ inputs.terraformAction }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Trigger nhs-notify-internal workflow deployment
        shell: bash
        run: |
          set -x

          DISPATCH_EVENT=$(jq -ncM \
            --arg infraRepoName ${{ inputs.infraRepoName }} \
            --arg releaseVersion ${{ inputs.releaseVersion }} \
            --arg targetEnvironment ${{ inputs.targetEnvironment }} \
            --arg targetAccountGroup ${{ inputs.targetAccountGroup }} \
            --arg targetComponent ${{ inputs.targetComponent }} \
            --arg terraformAction ${{ inputs.terraformAction }} \
            '{ "ref": "main",
              "inputs": {
                "infraRepoName", $infraRepoName,
                "releaseVersion", $releaseVersion,
                "targetEnvironment", $targetEnvironment,
                "targetAccountGroup", $targetAccountGroup,
                "targetComponent", $targetComponent,
                "terraformAction", $terraformAction
              }
            }')

          # Trigger The workflow
          curl -L \
            --fail \
            --silent \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/workflows/${{ inputs.targetWorkflow }}/dispatches" \
            -d "${DISPATCH_EVENT}"

          echo "Workflow triggered successfully. HTTP response. Waiting for the workflow to complete.."

          # Poll GitHub API to check the workflow status
          run_id=""
          for i in {1..12}; do
            run_id=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/runs?event=workflow_dispatch&status=in_progress" \
              | jq -r '.workflow_runs[0].id')

            if [[ -n "$run_id" && "$run_id" != null ]]; then
              echo "Found workflow run with ID: $run_id"
              echo "run_id=$run_id" >> $GITHUB_ENV
              break
            fi

            echo "Waiting for workflow to start..."
            sleep 10
          done

          if [[ -z "$run_id" || "$run_id" == null ]]; then
            echo "Failed to get the workflow run ID. Exiting."
            exit 1
          fi

          # Wait for workflow completion
          while true; do
            sleep 10
            status=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/runs/$run_id" \
              | jq -r '.status')

            conclusion=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/runs/$run_id" \
              | jq -r '.conclusion')

            if [ "$status" == "completed" ]; then
              if [ "$conclusion" == "success" ]; then
                echo "Workflow completed successfully."
                exit 0
              else
                echo "Workflow failed with conclusion: $conclusion"
                exit 1
              fi
            fi

            echo "Workflow still running..."
            sleep 20
          done

      - name: Download terraform outputs from triggered workflow deployment
        if: inputs.terraformAction == 'apply'
        run: |
          echo "Fetching artifact url for terraform-outputs-${{ inputs.targetComponent }}..."
          artifact_url=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/runs/$run_id/artifacts" \
            | jq -r '.artifacts[] | select(.name=="terraform-output-${{ inputs.targetComponent }}").archive_download_url')

          if [ -z "$artifact_url" ]; then
            echo "Error: Artifact terraform-outputs-${{ inputs.targetComponent }} not found."
            exit 1
          fi

          echo "Downloading artifact from $artifact_url"
          curl -L \
            -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -o terraform-output-${{ inputs.targetComponent }}.zip \
            $artifact_url

          echo "Extracting artifact..."
          unzip terraform-output-${{ inputs.targetComponent }}.zip

          echo "Artifact downloaded and extracted successfully."

      - name: Upload terraform outputs from triggered workflow deployment
        if: inputs.terraformAction == 'apply'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs-${{ inputs.targetComponent }}
          path: ./terraform_output.json
